SELECT
    ACQUISITION_COHORT,
    ACQUISITION_CHANNEL,
    CUSTOMER_TYPE,
    '30D'  AS LTV_INTERVAL,
    LTV_30D_PER_CUSTOMER  AS LTV_PER_CUSTOMER
FROM {{ ref('mart_subscription_ltv') }}

UNION ALL

SELECT
    ACQUISITION_COHORT,
    ACQUISITION_CHANNEL,
    CUSTOMER_TYPE,
    '90D'  AS LTV_INTERVAL,
    LTV_90D_PER_CUSTOMER  AS LTV_PER_CUSTOMER
FROM {{ ref('mart_subscription_ltv') }}

UNION ALL

SELECT
    ACQUISITION_COHORT,
    ACQUISITION_CHANNEL,
    CUSTOMER_TYPE,
    '180D' AS LTV_INTERVAL,
    LTV_180D_PER_CUSTOMER AS LTV_PER_CUSTOMER
FROM {{ ref('mart_subscription_ltv') }}

UNION ALL

SELECT
    ACQUISITION_COHORT,
    ACQUISITION_CHANNEL,
    CUSTOMER_TYPE,
    '365D' AS LTV_INTERVAL,
    LTV_365D_PER_CUSTOMER AS LTV_PER_CUSTOMER
FROM {{ ref('mart_subscription_ltv') }}